In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df=pd.DataFrame({'color':
['red','blue','green','green','red','blue'] 
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
#instance of encoder
#it will provide array directly no need to do to_array sparse_array=False
encoder=OneHotEncoder(sparse_output=False)

In [6]:
#perform fit & tranform , fit -> learns from categorical data & transform does transformation from categorical to data
encoded=encoder.fit_transform(df[['color']])

In [7]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [9]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [11]:
import seaborn as sns
df=sns.load_dataset('tips')

In [22]:
encoder_tips=encoder.fit_transform(df[['smoker']])

In [23]:
encoder_df_2=pd.DataFrame(encoder_tips,columns=encoder.get_feature_names_out())

In [24]:
encoder_df_2

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]