In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
df=pd.DataFrame({'color':
['red','blue','green','green','red','blue'] 
})

In [5]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
#instance of encoder
#it will provide array directly no need to do to_array sparse_array=False
encoder=OneHotEncoder(sparse_output=False)

In [19]:
#perform fit & tranform , fit -> learns from categorical data & transform does transformation from categorical to data
encoded=encoder.fit_transform(df[['color']])

In [20]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [21]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [22]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0