In [1]:
import numpy as np
import pandas as pd

In [2]:
#set the random seed for repoducability
np.random.seed(50)

In [3]:
n_samples=1000
class_0_ratio=0.9 #creating imbalanced dataset of 900,100
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0
n_class_0,n_class_1

(900, 100)

In [ ]:
''' loc is digit near to which mean is expected, scale is S.D to 1 and size of column & normal is have normal dist to achive bell curve
'''
class_0=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_0),
    'target':[0] * n_class_0
})
class_0

     feature_1  feature_2  target
0    -1.560352   1.901068       0
1    -0.030978   2.587077       0
2    -0.620928   0.945411       0
3    -1.464580   0.971237       0
4     1.411946   2.324330       0
..         ...        ...     ...
895  -0.436827   2.597436       0
896  -0.328299   0.604228       0
897   1.131414   2.664117       0
898  -0.250921   1.068361       0
899  -0.543287   2.407108       0

[900 rows x 3 columns]

In [ ]:
class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [7]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)
df

     feature_1  feature_2  target
0    -1.560352   1.901068       0
1    -0.030978   2.587077       0
2    -0.620928   0.945411       0
3    -1.464580   0.971237       0
4     1.411946   2.324330       0
..         ...        ...     ...
995   1.607211   1.376902       1
996   3.942472   2.068365       1
997   2.885720   2.189992       1
998   2.442306   0.881625       1
999   3.042787   1.203993       1

[1000 rows x 3 columns]

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [9]:
#upsample:
df_minority=df[df['target'] == 1]
df_majority=df[df['target'] == 0]

from sklearn.utils import resample
df_minority_unsampled=resample(df_minority,replace=True,n_samples=len(df_majority),random_state=34)
df_minority_unsampled.shape

(900, 3)

In [10]:
df_unsampled=pd.concat([df_majority,df_minority_unsampled])
df_unsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [12]:
#downsampling
class_0=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_0),
    'target':[0] * n_class_0
})

class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [13]:
df_majority_unsampled=resample(df_majority,replace=True,n_samples=len(df_minority),random_state=42)
df_majority_unsampled.shape

(100, 3)

In [14]:
df=pd.concat([df_minority,df_majority_unsampled])
df['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64