In [1]:
import pandas as pd
df=pd.read_csv('data.csv')

In [2]:
#first 5 rows
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [3]:
#last 5 rows
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [4]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [5]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [6]:
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [7]:
#isnull row wise
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [8]:
#null value by column -true/false
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [9]:
#fill null value with 0
df.fillna(0)
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [10]:
#fill null values with mean
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())

In [11]:
df.head(5)

         Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [12]:
df.isnull().any()

Date            False
Category        False
Value            True
Product         False
Sales            True
Region          False
Sales_fillNA    False
dtype: bool

In [13]:
#datatypes of column
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [14]:
#column rename
df.rename(columns={'Date':'Sales Date'})
df.head()

         Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [15]:
#chnage datatype of column
df['Value_New_dt']=df["Value"].fillna(df['Value'].mean()).astype(int)

In [16]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
Value_New_dt      int64
dtype: object

In [17]:
#function apply on any dataframe
df['function_value']=df['Value_New_dt'].apply(lambda x:x*2)

In [18]:
df.head()

,Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_New_dt,function_value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52

In [19]:
#data aggregation and grouping
grouped_mean=df.groupby('Product')['Value'].mean()
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [20]:
#sum based on 2 categorical columns
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
grouped_sum

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [21]:
#multiple agg function
grouped_agg=df.groupby('Product')['Value'].agg(['sum','mean','count'])
grouped_agg

            sum       mean  count
Product
Product1  647.0  46.214286     14
Product2  792.0  52.800000     15
Product3  993.0  55.166667     18

In [31]:
#merge and join dataframes
df1=pd.DataFrame({'Key':['A','B','C'],'Value':[1,2,3]})
df1
df2=pd.DataFrame({'Key':['A','B','D'],'Value':[4,5,6]})
df2
#merge dataframes on column

pd.merge(df1,df2,on='Key',how='inner')

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

In [23]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [24]:
pd.merge(df1,df2,on='Key',how='left')

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [25]:
pd.merge(df1,df2,on='Key',how='right')

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6