In [21]:
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(series.dtype)

0    1
1    2
2    3
3    4
4    5
dtype: int64
int64

In [22]:
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [23]:
#manually specify data and index
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [24]:
#dataframe : 2D & heterogenous
data={
    'Name': ['Pinal','John','Jack'],
    'Age':[25,30,46],
    'City': ['nashik','pune','mumbai']
}

df=pd.DataFrame(data)
df

    Name  Age    City
0  Pinal   25  nashik
1   John   30    pune
2   Jack   46  mumbai

In [25]:
#dataframe from list of dict
data=[
    {'Name':'p','age':24,'city':'nashik'},
    {'Name':'r','age':27,'city':'dubai'},
    {'Name':'j','age':35,'city':'NY'}
]
df=pd.DataFrame(data)
df

  Name  age    city
0    p   24  nashik
1    r   27   dubai
2    j   35      NY

In [26]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [27]:
#starting top 2 rows
df.head(2)
#starting bottom 1 row
df.tail(1)

  Name  age city
2    j   35   NY

In [28]:
#row speific
df.loc[0]

Name         p
age         24
city    nashik
Name: 0, dtype: object

In [44]:
#column specific
print(df)

df.iloc[0]

  Name    city        salary
0    p  nashik    1000000000
1    r   dubai  500000000000
2    j      NY        450000

Name               p
city          nashik
salary    1000000000
Name: 0, dtype: object

In [45]:
df.iloc[0][0]

/var/folders/0q/gm_bp63n07v537jt_8b1wzz00000gn/T/ipykernel_8511/3629555008.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'p'

In [46]:
df.loc[0][0]

/var/folders/0q/gm_bp63n07v537jt_8b1wzz00000gn/T/ipykernel_8511/2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'p'

In [32]:
#accesing specific element
df.at[1,'Name']

'r'

In [33]:
df.iat[2,2]

'NY'

In [34]:
df["salary"]=[1000000000,500000000000,450000]
df

  Name  age    city        salary
0    p   24  nashik    1000000000
1    r   27   dubai  500000000000
2    j   35      NY        450000

In [35]:
#drop column
df.drop('age',axis=1,inplace=True)

In [36]:
df

  Name    city        salary
0    p  nashik    1000000000
1    r   dubai  500000000000
2    j      NY        450000

In [37]:
df

  Name    city        salary
0    p  nashik    1000000000
1    r   dubai  500000000000
2    j      NY        450000

In [38]:
#provides statistical summary of the dataframe
df.describe()

             salary
count  3.000000e+00
mean   1.670002e+11
std    2.883868e+11
min    4.500000e+05
25%    5.002250e+08
50%    1.000000e+09
75%    2.505000e+11
max    5.000000e+11