In [2]:
'''### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.'''

import numpy as np
import pandas as pd

df=pd.DataFrame(
    np.random.randint(1,100,size=(6,4)),
    columns=['A','B','C','D']
)
df.set_index(('A'),inplace=True)
df

     B   C   D
A
25  84  81  65
40  43  24  22
72  92  65  79
8   49  84  82
16  86  26  28
84  61  55  68

In [3]:
'''2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.'''
df=pd.DataFrame(
    np.random.randint(1,10,size=(3,3)),
    columns=['A','B','C'],
    index=['X','Y','Z']
)
print(df)

print(df.loc['Y','B'])

   A  B  C
X  2  9  8
Y  9  4  6
Z  2  4  3
4

In [4]:
'''1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.'''

df=pd.DataFrame(
    np.random.randint(1,100,size=(5,3))
)
print(df)

df[3]=df[1]*df[2]
print("after df = ")
print(df)

    0   1   2
0  37  40  73
1  55  90  94
2  89  71  42
3  42  89  95
4  84  13  19
after df =
    0   1   2     3
0  37  40  73  2920
1  55  90  94  8460
2  89  71  42  2982
3  42  89  95  8455
4  84  13  19   247

In [5]:
'''Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.'''
print("column wise sum = \n",df.sum(axis=0))
print("row wise sum = \n",df.sum(axis=1))

column wise sum =
 0      307
1      303
2      323
3    23064
dtype: int64
row wise sum =
 0    3070
1    8699
2    3184
3    8681
4     363
dtype: int64

In [6]:
'''### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.'''

df=pd.DataFrame(
    np.random.randint(1,100,size=(5,3)),
)
print(df)
df.iat[0,1]=None
df.iat[1,2]=None
df.iat[3,0]=None
df.iat[4,2]=None
print("after adding NaN")
df

    0   1   2
0  47  98  14
1   3  92  65
2  74  50  74
3  45  81  91
4  64  90  53
after adding NaN

      0     1     2
0  47.0   NaN  14.0
1   3.0  92.0   NaN
2  74.0  50.0  74.0
3   NaN  81.0  91.0
4  64.0  90.0   NaN

In [7]:
df[0]=df[0].fillna(df[0].mean())
df[1]=df[1].fillna(df[1].mean())
df[2]=df[2].fillna(df[2].mean())

In [8]:
df

      0      1          2
0  47.0  78.25  14.000000
1   3.0  92.00  59.666667
2  74.0  50.00  74.000000
3  47.0  81.00  91.000000
4  64.0  90.00  59.666667

In [9]:
'''Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.'''

df=pd.DataFrame(
    np.random.randint(1,100,size=(5,3)),
)
print(df)
df.iat[0,1]=None
df.iat[1,2]=None
df.iat[3,0]=None
df.iat[4,2]=None
print("after adding NaN")
df

    0   1   2
0   3  70  60
1  20  57  19
2  43  67  62
3  92  51  58
4   4  85  53
after adding NaN

      0     1     2
0   3.0   NaN  60.0
1  20.0  57.0   NaN
2  43.0  67.0  62.0
3   NaN  51.0  58.0
4   4.0  85.0   NaN

In [10]:

df.isnull()
df.dropna(inplace=True)
df

      0     1     2
2  43.0  67.0  62.0

In [11]:
'''### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.'''

data=np.array([
   ('A',10),
   ('B',33),
   ('C',45),
   ('A',65),
   ('B',22),
   ('B',12),
   ('B',56),
   ('C',320) 
],dtype=[('Category','U10'),('Value','i4')])

df=pd.DataFrame(data)
groupedmean=df.groupby('Category')['Value'].mean()
groupedsum=df.groupby('Category')['Value'].sum()
print("mean = ",groupedmean)
print("groupedsum = ",groupedsum)

mean =  Category
A     37.50
B     30.75
C    182.50
Name: Value, dtype: float64
groupedsum =  Category
A     75
B    123
C    365
Name: Value, dtype: int32

In [12]:
'''2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.'''
df2=pd.DataFrame({'Category':np.random.choice(['A','B','C'],size=100),'Value':np.random.randint(1,100,size=100),'Sales':np.random.randint(1,100,size=100)})
salesgrouped=df2.groupby(['Category'])['Sales'].sum()
salesgrouped

Category
A    1908
B    1986
C     958
Name: Sales, dtype: int64

In [13]:
'''1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.'''
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  8 non-null      object
 1   Value     8 non-null      int32
dtypes: int32(1), object(1)
memory usage: 228.0+ bytes

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  100 non-null    object
 1   Value     100 non-null    int64
 2   Sales     100 non-null    int64
dtypes: int64(2), object(1)
memory usage: 2.5+ KB

In [15]:
df3=df
df3.loc[3,'Value']=567
df3.loc[7,'Value']=234
df3.loc[0,'Category']='C'
merged_data=pd.merge(df,df3,on='Category',how='inner')
merged_data

   Category  Value_x  Value_y
0         C       10       10
1         C       10       45
2         C       10      234
3         B       33       33
4         B       33       22
5         B       33       12
6         B       33       56
7         C       45       10
8         C       45       45
9         C       45      234
10        A      567      567
11        B       22       33
12        B       22       22
13        B       22       12
14        B       22       56
15        B       12       33
16        B       12       22
17        B       12       12
18        B       12       56
19        B       56       33
20        B       56       22
21        B       56       12
22        B       56       56
23        C      234       10
24        C      234       45
25        C      234      234

In [16]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

# Concatenate the DataFrames along the rows
concat_rows = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame (rows):")
print(concat_rows)

# Concatenate the DataFrames along the columns
concat_columns = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (columns):")
print(concat_columns)

DataFrame 1:
    A   B
0  44  14
1  11  67
2  96  23
DataFrame 2:
    C   D
0  70  39
1  24  53
2  92  56
Concatenated DataFrame (rows):
      A     B     C     D
0  44.0  14.0   NaN   NaN
1  11.0  67.0   NaN   NaN
2  96.0  23.0   NaN   NaN
0   NaN   NaN  70.0  39.0
1   NaN   NaN  24.0  53.0
2   NaN   NaN  92.0  56.0
Concatenated DataFrame (columns):
    A   B   C   D
0  44  14  70  39
1  11  67  24  53
2  96  23  92  56

In [ ]:
'''2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.'''


df1=pd.DataFrame({'P':np.random.randint(1,100,size=3),'Q':np.random.randint(1,100,size=3)})
df2=pd.DataFrame({'R':np.random.randint(1,100,size=3),'S':np.random.randint(1,100,size=3)})

concat_rows=pd.concat([df1,df2],axis=0)
concat_cols=pd.concat([df1,df2],axis=1)

print("rows = \n",concat_rows)
print("columns = \n",concat_columns)

rows =
       P     Q     R     S
0  16.0  10.0   NaN   NaN
1   8.0  34.0   NaN   NaN
2  96.0  49.0   NaN   NaN
0   NaN   NaN  85.0  55.0
1   NaN   NaN  97.0  79.0
2   NaN   NaN  96.0  89.0
columns =
     A   B   C   D
0  44  14  70  39
1  11  67  24  53
2  96  23  92  56

In [46]:
'''### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.'''

date_values=pd.date_range(start='2026-01-01',end='2026-12-31',freq='D')
df=pd.DataFrame(date_values,columns=['date_value'])
df['values']=np.random.randint(1,100,size=len(df['date_value']))
#setting datevalue as index
df.set_index(df['date_value'],inplace=True)
print(df)
df.resample('ME').mean()

           date_value  values
date_value
2026-01-01 2026-01-01       6
2026-01-02 2026-01-02       3
2026-01-03 2026-01-03      71
2026-01-04 2026-01-04      96
2026-01-05 2026-01-05      38
...               ...     ...
2026-12-27 2026-12-27      98
2026-12-28 2026-12-28      90
2026-12-29 2026-12-29      11
2026-12-30 2026-12-30      90
2026-12-31 2026-12-31      41

[365 rows x 2 columns]

                    date_value     values
date_value
2026-01-31 2026-01-16 00:00:00  46.612903
2026-02-28 2026-02-14 12:00:00  48.428571
2026-03-31 2026-03-16 00:00:00  50.935484
2026-04-30 2026-04-15 12:00:00  51.666667
2026-05-31 2026-05-16 00:00:00  48.741935
2026-06-30 2026-06-15 12:00:00  52.566667
2026-07-31 2026-07-16 00:00:00  50.677419
2026-08-31 2026-08-16 00:00:00  41.451613
2026-09-30 2026-09-15 12:00:00  60.966667
2026-10-31 2026-10-16 00:00:00  51.741935
2026-11-30 2026-11-15 12:00:00  42.333333
2026-12-31 2026-12-16 00:00:00  51.032258

In [ ]:
'''Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.'''
#rolling mean
date_values=pd.date_range(start='2021-01-01',end='2021-12-31',freq='D')
df=pd.DataFrame(date_values,columns=['date_column'])
df['num']=np.random.randint(0,100,size=len(date_values),dtype=int)

df.set_index('date_column',inplace=True)
df.rolling(window=7).mean()

                   num
date_column
2021-01-01         NaN
2021-01-02         NaN
2021-01-03         NaN
2021-01-04         NaN
2021-01-05         NaN
...                ...
2021-12-27   50.428571
2021-12-28   56.285714
2021-12-29   47.000000
2021-12-30   37.000000
2021-12-31   47.285714

[365 rows x 1 columns]

In [91]:
'''
1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.'''

arrays=[['A','B','A','B','E'],['one','two','one','two','one']]
index=pd.MultiIndex.from_arrays(arrays,names=['Category','SubCategory'])
df=pd.DataFrame(np.random.randint(1,100,size=(5,3)),index=index,columns=['V1','V2','V3'])
print(df.columns)
print(df.index)

print("output = ",df.loc['A'])
print()
print("output = ",df.loc[('B','two')])

sum_val=df.groupby(['Category','SubCategory']).sum()
print("sum value  = \n",sum_val)

Index(['V1', 'V2', 'V3'], dtype='object')
MultiIndex([('A', 'one'),
            ('B', 'two'),
            ('A', 'one'),
            ('B', 'two'),
            ('E', 'one')],
           names=['Category', 'SubCategory'])
output =               V1  V2  V3
SubCategory
one          89  47  84
one          45   6  75

output =                        V1  V2  V3
Category SubCategory
B        two          29  52  21
         two          13  86  94
sum value  =
                        V1   V2   V3
Category SubCategory
A        one          134   53  159
B        two           42  138  115
E        one           61   66   72

/var/folders/0q/gm_bp63n07v537jt_8b1wzz00000gn/T/ipykernel_12215/2300135718.py:13: PerformanceWarning: indexing past lexsort depth may impact performance.
  print("output = ",df.loc[('B','two')])

In [92]:
'''### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.'''

str_series=pd.Series(['apple','banana','orange','blueberry','avacado'])
print(str_series.str.upper())

0        APPLE
1       BANANA
2       ORANGE
3    BLUEBERRY
4      AVACADO
dtype: object

In [93]:
'''2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.
'''
print(str_series.str[:3])

0    app
1    ban
2    ora
3    blu
4    ava
dtype: object